require("impatient")

require("core.settings")
require("core.keymaps")
require("core.colemak")

require("core.plugins")
require("configs.notify").config()
require("configs.noice").config()
require("configs.alpha").config()
require("configs.nvimtree").config()
require("configs.treesitter").config()
require("configs.lualine").config()
require("configs.bufferline").config()
require("configs.luasnip").config()
require("configs.mason").config()
require("configs.masonlspconfig").config()
require("configs.lspconfig").config()
require("configs.telescope").config()
require("configs.indentline").config()
require("configs.fidget").config()
require("configs.null-ls").config()
require("configs.hop").config()
require("configs.lastplace").config()
require("configs.gitsigns").config()
require("configs.todo-comments").config()
require("configs.scrollbar").config()
require("configs.toggleterm").config()
require("configs.nvimcolorizer").config()
require("configs.undotree").config()
require("configs.surround").config()

require("configs.dap").config()
require("configs.gopher").config()

-- theme
--require("configs.theme.gruvbox").config()
require("configs.theme.kanagawa").config()
